[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "
vicmd_symbol = "[V](bold green) "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"

[git_status]
conflicted = "⚔️ "
ahead = "🏎️ 💨 x${count} "
behind = "🐢 ×${count} "
diverged = "🔱 🏎️ 💨 ×${ahead_count} 🐢 ×${behind_count} "
untracked = "🛤️ ×${count} "
stashed = "📦 "
modified = "📝×${count} "
staged = "🗃️ ×${count} "
renamed = "📛×${count} "
deleted = "🗑️×${count} "
style = "bright-white"
format = "$all_status$ahead_behind"

[golang]
format = " via [🏎💨 $version](bold cyan) "
